<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>Project Aeon - Experimental</Title>
    <Description>A work-in-progress package for experimental functionality undergoing testing on Project Aeon experiments.</Description>
    <PackageTags>$(PackageTags) Experimental</PackageTags>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="**\*.bonsai" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aeon.Acquisition" Version="0.7.0" />
  </ItemGroup>

</Project>
