//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Aeon.Ephys
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Any supported ONIX headstage, selected by its discriminator.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Newtonsoft.Json.JsonConverter(typeof(JsonInheritanceConverter), "DiscriminatorType")]
    [YamlDiscriminator("DiscriminatorType")]
    [JsonInheritanceAttribute("NeuropixelsV2eHeadstage", typeof(NeuropixelsV2eHeadstage))]
    [JsonInheritanceAttribute("NeuropixelsV2eBetaHeadstage", typeof(NeuropixelsV2eBetaHeadstage))]
    [JsonInheritanceAttribute("Headstage64", typeof(Headstage64))]
    [System.ComponentModel.DescriptionAttribute("Any supported ONIX headstage, selected by its discriminator.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Headstage
    {
    
        public Headstage()
        {
        }
    
        protected Headstage(Headstage other)
        {
        }
    
        public System.IObservable<Headstage> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Headstage(this)));
        }
    
        public System.IObservable<Headstage> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Headstage(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            return false;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// A 64-channel headstage carrying an RHD2164 amplifier, IMU and stimulators.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("A 64-channel headstage carrying an RHD2164 amplifier, IMU and stimulators.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Headstage64 : Headstage
    {
    
        private OpenEphys.Onix1.PortName _port;
    
        private OpenEphys.Onix1.AutoPortVoltage _portVoltage;
    
        private int _bufferSize;
    
        private OpenEphys.Onix1.ConfigureRhd2164 _rhd2164;
    
        private OpenEphys.Onix1.ConfigureBno055 _bno055;
    
        private OpenEphys.Onix1.ConfigureTS4231V1 _ts4231;
    
        private OpenEphys.Onix1.ConfigureHeadstage64ElectricalStimulator _electricalStimulator;
    
        private OpenEphys.Onix1.ConfigureHeadstage64OpticalStimulator _opticalStimulator;
    
        public Headstage64()
        {
            _port = OpenEphys.Onix1.PortName.PortA;
            _portVoltage = new OpenEphys.Onix1.AutoPortVoltage();
            _bufferSize = 30;
            _rhd2164 = new OpenEphys.Onix1.ConfigureRhd2164();
            _bno055 = new OpenEphys.Onix1.ConfigureBno055();
            _ts4231 = new OpenEphys.Onix1.ConfigureTS4231V1();
            _electricalStimulator = new OpenEphys.Onix1.ConfigureHeadstage64ElectricalStimulator();
            _opticalStimulator = new OpenEphys.Onix1.ConfigureHeadstage64OpticalStimulator();
        }
    
        protected Headstage64(Headstage64 other) : 
                base(other)
        {
            _port = other._port;
            _portVoltage = other._portVoltage;
            _bufferSize = other._bufferSize;
            _rhd2164 = other._rhd2164;
            _bno055 = other._bno055;
            _ts4231 = other._ts4231;
            _electricalStimulator = other._electricalStimulator;
            _opticalStimulator = other._opticalStimulator;
        }
    
        /// <summary>
        /// The breakout-board port the headstage is connected to.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("Port")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Port")]
        [System.ComponentModel.DescriptionAttribute("The breakout-board port the headstage is connected to.")]
        public OpenEphys.Onix1.PortName Port
        {
            get
            {
                return _port;
            }
            set
            {
                _port = value;
            }
        }
    
        /// <summary>
        /// Port voltage settings for the headstage link.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("PortVoltage", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="PortVoltage")]
        [System.ComponentModel.DescriptionAttribute("Port voltage settings for the headstage link.")]
        public OpenEphys.Onix1.AutoPortVoltage PortVoltage
        {
            get
            {
                return _portVoltage;
            }
            set
            {
                _portVoltage = value;
            }
        }
    
        /// <summary>
        /// Number of frames buffered per probe read.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("BufferSize")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="BufferSize")]
        [System.ComponentModel.DescriptionAttribute("Number of frames buffered per probe read.")]
        public int BufferSize
        {
            get
            {
                return _bufferSize;
            }
            set
            {
                _bufferSize = value;
            }
        }
    
        /// <summary>
        /// Configuration for the RHD2164 amplifier.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("Rhd2164", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Rhd2164")]
        [System.ComponentModel.DescriptionAttribute("Configuration for the RHD2164 amplifier.")]
        public OpenEphys.Onix1.ConfigureRhd2164 Rhd2164
        {
            get
            {
                return _rhd2164;
            }
            set
            {
                _rhd2164 = value;
            }
        }
    
        /// <summary>
        /// Configuration for the inertial measurement unit.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("Bno055", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Bno055")]
        [System.ComponentModel.DescriptionAttribute("Configuration for the inertial measurement unit.")]
        public OpenEphys.Onix1.ConfigureBno055 Bno055
        {
            get
            {
                return _bno055;
            }
            set
            {
                _bno055 = value;
            }
        }
    
        /// <summary>
        /// Configuration for the optical position sensor.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("Ts4231", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Ts4231")]
        [System.ComponentModel.DescriptionAttribute("Configuration for the optical position sensor.")]
        public OpenEphys.Onix1.ConfigureTS4231V1 Ts4231
        {
            get
            {
                return _ts4231;
            }
            set
            {
                _ts4231 = value;
            }
        }
    
        /// <summary>
        /// Configuration for the electrical stimulator.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("ElectricalStimulator", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ElectricalStimulator")]
        [System.ComponentModel.DescriptionAttribute("Configuration for the electrical stimulator.")]
        public OpenEphys.Onix1.ConfigureHeadstage64ElectricalStimulator ElectricalStimulator
        {
            get
            {
                return _electricalStimulator;
            }
            set
            {
                _electricalStimulator = value;
            }
        }
    
        /// <summary>
        /// Configuration for the optical stimulator.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("OpticalStimulator", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="OpticalStimulator")]
        [System.ComponentModel.DescriptionAttribute("Configuration for the optical stimulator.")]
        public OpenEphys.Onix1.ConfigureHeadstage64OpticalStimulator OpticalStimulator
        {
            get
            {
                return _opticalStimulator;
            }
            set
            {
                _opticalStimulator = value;
            }
        }
    
        public System.IObservable<Headstage64> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Headstage64(this)));
        }
    
        public System.IObservable<Headstage64> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Headstage64(this));
        }
    
        protected override bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            if (base.PrintMembers(stringBuilder))
            {
                stringBuilder.Append(", ");
            }
            stringBuilder.Append("Port = " + _port + ", ");
            stringBuilder.Append("PortVoltage = " + _portVoltage + ", ");
            stringBuilder.Append("BufferSize = " + _bufferSize + ", ");
            stringBuilder.Append("Rhd2164 = " + _rhd2164 + ", ");
            stringBuilder.Append("Bno055 = " + _bno055 + ", ");
            stringBuilder.Append("Ts4231 = " + _ts4231 + ", ");
            stringBuilder.Append("ElectricalStimulator = " + _electricalStimulator + ", ");
            stringBuilder.Append("OpticalStimulator = " + _opticalStimulator);
            return true;
        }
    }


    /// <summary>
    /// One of the two probes addressed by a Neuropixels 2.0e beta headstage.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("One of the two probes addressed by a Neuropixels 2.0e beta headstage.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class NeuropixelsV2BetaProbe
    {
    
        private bool _enable;
    
        private bool _enableLed;
    
        private OpenEphys.Onix1.NeuropixelsV2QuadShankProbeConfiguration _probeConfiguration;
    
        public NeuropixelsV2BetaProbe()
        {
            _enable = false;
            _enableLed = true;
            _probeConfiguration = new OpenEphys.Onix1.NeuropixelsV2QuadShankProbeConfiguration();
        }
    
        protected NeuropixelsV2BetaProbe(NeuropixelsV2BetaProbe other)
        {
            _enable = other._enable;
            _enableLed = other._enableLed;
            _probeConfiguration = other._probeConfiguration;
        }
    
        /// <summary>
        /// Whether to acquire data from this probe.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("Enable")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Enable")]
        [System.ComponentModel.DescriptionAttribute("Whether to acquire data from this probe.")]
        public bool Enable
        {
            get
            {
                return _enable;
            }
            set
            {
                _enable = value;
            }
        }
    
        /// <summary>
        /// Whether to enable the probe's LED.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("EnableLed")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="EnableLed")]
        [System.ComponentModel.DescriptionAttribute("Whether to enable the probe\'s LED.")]
        public bool EnableLed
        {
            get
            {
                return _enableLed;
            }
            set
            {
                _enableLed = value;
            }
        }
    
        /// <summary>
        /// Calibration and reference settings for this probe.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("ProbeConfiguration", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ProbeConfiguration")]
        [System.ComponentModel.DescriptionAttribute("Calibration and reference settings for this probe.")]
        public OpenEphys.Onix1.NeuropixelsV2QuadShankProbeConfiguration ProbeConfiguration
        {
            get
            {
                return _probeConfiguration;
            }
            set
            {
                _probeConfiguration = value;
            }
        }
    
        public System.IObservable<NeuropixelsV2BetaProbe> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new NeuropixelsV2BetaProbe(this)));
        }
    
        public System.IObservable<NeuropixelsV2BetaProbe> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new NeuropixelsV2BetaProbe(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Enable = " + _enable + ", ");
            stringBuilder.Append("EnableLed = " + _enableLed + ", ");
            stringBuilder.Append("ProbeConfiguration = " + _probeConfiguration);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// One of the two probes addressed by a Neuropixels 2.0e headstage.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("One of the two probes addressed by a Neuropixels 2.0e headstage.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class NeuropixelsV2Probe
    {
    
        private bool _enable;
    
        private OpenEphys.Onix1.NeuropixelsV2QuadShankProbeConfiguration _probeConfiguration;
    
        public NeuropixelsV2Probe()
        {
            _enable = false;
            _probeConfiguration = new OpenEphys.Onix1.NeuropixelsV2QuadShankProbeConfiguration();
        }
    
        protected NeuropixelsV2Probe(NeuropixelsV2Probe other)
        {
            _enable = other._enable;
            _probeConfiguration = other._probeConfiguration;
        }
    
        /// <summary>
        /// Whether to acquire data from this probe.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("Enable")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Enable")]
        [System.ComponentModel.DescriptionAttribute("Whether to acquire data from this probe.")]
        public bool Enable
        {
            get
            {
                return _enable;
            }
            set
            {
                _enable = value;
            }
        }
    
        /// <summary>
        /// Calibration and reference settings for this probe.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("ProbeConfiguration", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ProbeConfiguration")]
        [System.ComponentModel.DescriptionAttribute("Calibration and reference settings for this probe.")]
        public OpenEphys.Onix1.NeuropixelsV2QuadShankProbeConfiguration ProbeConfiguration
        {
            get
            {
                return _probeConfiguration;
            }
            set
            {
                _probeConfiguration = value;
            }
        }
    
        public System.IObservable<NeuropixelsV2Probe> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new NeuropixelsV2Probe(this)));
        }
    
        public System.IObservable<NeuropixelsV2Probe> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new NeuropixelsV2Probe(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Enable = " + _enable + ", ");
            stringBuilder.Append("ProbeConfiguration = " + _probeConfiguration);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// A Neuropixels 2.0e beta headstage carrying two quad-shank probes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("A Neuropixels 2.0e beta headstage carrying two quad-shank probes.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class NeuropixelsV2eBetaHeadstage : Headstage
    {
    
        private OpenEphys.Onix1.PortName _port;
    
        private OpenEphys.Onix1.AutoPortVoltage _portVoltage;
    
        private int _bufferSize;
    
        private bool _trackingLed;
    
        private NeuropixelsV2BetaProbe _probeA;
    
        private NeuropixelsV2BetaProbe _probeB;
    
        public NeuropixelsV2eBetaHeadstage()
        {
            _port = OpenEphys.Onix1.PortName.PortA;
            _portVoltage = new OpenEphys.Onix1.AutoPortVoltage();
            _bufferSize = 30;
            _trackingLed = false;
            _probeA = new NeuropixelsV2BetaProbe();
            _probeB = new NeuropixelsV2BetaProbe();
        }
    
        protected NeuropixelsV2eBetaHeadstage(NeuropixelsV2eBetaHeadstage other) : 
                base(other)
        {
            _port = other._port;
            _portVoltage = other._portVoltage;
            _bufferSize = other._bufferSize;
            _trackingLed = other._trackingLed;
            _probeA = other._probeA;
            _probeB = other._probeB;
        }
    
        /// <summary>
        /// The breakout-board port the headstage is connected to.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("Port")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Port")]
        [System.ComponentModel.DescriptionAttribute("The breakout-board port the headstage is connected to.")]
        public OpenEphys.Onix1.PortName Port
        {
            get
            {
                return _port;
            }
            set
            {
                _port = value;
            }
        }
    
        /// <summary>
        /// Port voltage settings for the headstage link.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("PortVoltage", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="PortVoltage")]
        [System.ComponentModel.DescriptionAttribute("Port voltage settings for the headstage link.")]
        public OpenEphys.Onix1.AutoPortVoltage PortVoltage
        {
            get
            {
                return _portVoltage;
            }
            set
            {
                _portVoltage = value;
            }
        }
    
        /// <summary>
        /// Number of frames buffered per probe read.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("BufferSize")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="BufferSize")]
        [System.ComponentModel.DescriptionAttribute("Number of frames buffered per probe read.")]
        public int BufferSize
        {
            get
            {
                return _bufferSize;
            }
            set
            {
                _bufferSize = value;
            }
        }
    
        /// <summary>
        /// Whether to enable the headstage's tracking LED.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("TrackingLed")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="TrackingLed")]
        [System.ComponentModel.DescriptionAttribute("Whether to enable the headstage\'s tracking LED.")]
        public bool TrackingLed
        {
            get
            {
                return _trackingLed;
            }
            set
            {
                _trackingLed = value;
            }
        }
    
        /// <summary>
        /// Configuration for probe A.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("ProbeA", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ProbeA")]
        [System.ComponentModel.DescriptionAttribute("Configuration for probe A.")]
        public NeuropixelsV2BetaProbe ProbeA
        {
            get
            {
                return _probeA;
            }
            set
            {
                _probeA = value;
            }
        }
    
        /// <summary>
        /// Configuration for probe B.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("ProbeB", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ProbeB")]
        [System.ComponentModel.DescriptionAttribute("Configuration for probe B.")]
        public NeuropixelsV2BetaProbe ProbeB
        {
            get
            {
                return _probeB;
            }
            set
            {
                _probeB = value;
            }
        }
    
        public System.IObservable<NeuropixelsV2eBetaHeadstage> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new NeuropixelsV2eBetaHeadstage(this)));
        }
    
        public System.IObservable<NeuropixelsV2eBetaHeadstage> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new NeuropixelsV2eBetaHeadstage(this));
        }
    
        protected override bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            if (base.PrintMembers(stringBuilder))
            {
                stringBuilder.Append(", ");
            }
            stringBuilder.Append("Port = " + _port + ", ");
            stringBuilder.Append("PortVoltage = " + _portVoltage + ", ");
            stringBuilder.Append("BufferSize = " + _bufferSize + ", ");
            stringBuilder.Append("TrackingLed = " + _trackingLed + ", ");
            stringBuilder.Append("ProbeA = " + _probeA + ", ");
            stringBuilder.Append("ProbeB = " + _probeB);
            return true;
        }
    }


    /// <summary>
    /// A Neuropixels 2.0e headstage carrying two quad-shank probes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("A Neuropixels 2.0e headstage carrying two quad-shank probes.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class NeuropixelsV2eHeadstage : Headstage
    {
    
        private OpenEphys.Onix1.PortName _port;
    
        private OpenEphys.Onix1.AutoPortVoltage _portVoltage;
    
        private int _bufferSize;
    
        private NeuropixelsV2Probe _probeA;
    
        private NeuropixelsV2Probe _probeB;
    
        public NeuropixelsV2eHeadstage()
        {
            _port = OpenEphys.Onix1.PortName.PortA;
            _portVoltage = new OpenEphys.Onix1.AutoPortVoltage();
            _bufferSize = 30;
            _probeA = new NeuropixelsV2Probe();
            _probeB = new NeuropixelsV2Probe();
        }
    
        protected NeuropixelsV2eHeadstage(NeuropixelsV2eHeadstage other) : 
                base(other)
        {
            _port = other._port;
            _portVoltage = other._portVoltage;
            _bufferSize = other._bufferSize;
            _probeA = other._probeA;
            _probeB = other._probeB;
        }
    
        /// <summary>
        /// The breakout-board port the headstage is connected to.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("Port")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Port")]
        [System.ComponentModel.DescriptionAttribute("The breakout-board port the headstage is connected to.")]
        public OpenEphys.Onix1.PortName Port
        {
            get
            {
                return _port;
            }
            set
            {
                _port = value;
            }
        }
    
        /// <summary>
        /// Port voltage settings for the headstage link.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("PortVoltage", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="PortVoltage")]
        [System.ComponentModel.DescriptionAttribute("Port voltage settings for the headstage link.")]
        public OpenEphys.Onix1.AutoPortVoltage PortVoltage
        {
            get
            {
                return _portVoltage;
            }
            set
            {
                _portVoltage = value;
            }
        }
    
        /// <summary>
        /// Number of frames buffered per probe read.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("BufferSize")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="BufferSize")]
        [System.ComponentModel.DescriptionAttribute("Number of frames buffered per probe read.")]
        public int BufferSize
        {
            get
            {
                return _bufferSize;
            }
            set
            {
                _bufferSize = value;
            }
        }
    
        /// <summary>
        /// Configuration for probe A.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("ProbeA", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ProbeA")]
        [System.ComponentModel.DescriptionAttribute("Configuration for probe A.")]
        public NeuropixelsV2Probe ProbeA
        {
            get
            {
                return _probeA;
            }
            set
            {
                _probeA = value;
            }
        }
    
        /// <summary>
        /// Configuration for probe B.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("ProbeB", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ProbeB")]
        [System.ComponentModel.DescriptionAttribute("Configuration for probe B.")]
        public NeuropixelsV2Probe ProbeB
        {
            get
            {
                return _probeB;
            }
            set
            {
                _probeB = value;
            }
        }
    
        public System.IObservable<NeuropixelsV2eHeadstage> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new NeuropixelsV2eHeadstage(this)));
        }
    
        public System.IObservable<NeuropixelsV2eHeadstage> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new NeuropixelsV2eHeadstage(this));
        }
    
        protected override bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            if (base.PrintMembers(stringBuilder))
            {
                stringBuilder.Append(", ");
            }
            stringBuilder.Append("Port = " + _port + ", ");
            stringBuilder.Append("PortVoltage = " + _portVoltage + ", ");
            stringBuilder.Append("BufferSize = " + _bufferSize + ", ");
            stringBuilder.Append("ProbeA = " + _probeA + ", ");
            stringBuilder.Append("ProbeB = " + _probeB);
            return true;
        }
    }


    /// <summary>
    /// Top-level ONIX electrophysiology configuration loaded from YAML.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Top-level ONIX electrophysiology configuration loaded from YAML.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class EphysConfiguration
    {
    
        private Headstage _headstage;
    
        private OpenEphys.Onix1.ConfigureHarpSyncInput _harpInput;
    
        public EphysConfiguration()
        {
            _harpInput = new OpenEphys.Onix1.ConfigureHarpSyncInput();
        }
    
        protected EphysConfiguration(EphysConfiguration other)
        {
            _headstage = other._headstage;
            _harpInput = other._harpInput;
        }
    
        /// <summary>
        /// Configuration for the connected headstage.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("Headstage", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Headstage")]
        [System.ComponentModel.DescriptionAttribute("Configuration for the connected headstage.")]
        public Headstage Headstage
        {
            get
            {
                return _headstage;
            }
            set
            {
                _headstage = value;
            }
        }
    
        /// <summary>
        /// Configuration for the breakout board's Harp synchronisation input.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("HarpInput", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="HarpInput")]
        [System.ComponentModel.DescriptionAttribute("Configuration for the breakout board\'s Harp synchronisation input.")]
        public OpenEphys.Onix1.ConfigureHarpSyncInput HarpInput
        {
            get
            {
                return _harpInput;
            }
            set
            {
                _harpInput = value;
            }
        }
    
        public System.IObservable<EphysConfiguration> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new EphysConfiguration(this)));
        }
    
        public System.IObservable<EphysConfiguration> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new EphysConfiguration(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Headstage = " + _headstage + ", ");
            stringBuilder.Append("HarpInput = " + _harpInput);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.9.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Interface, AllowMultiple = true)]
    internal class JsonInheritanceAttribute : System.Attribute
    {
        public JsonInheritanceAttribute(string key, System.Type type)
        {
            Key = key;
            Type = type;
        }

        public string Key { get; private set; }

        public System.Type Type { get; private set; }
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.9.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public class JsonInheritanceConverter : Newtonsoft.Json.JsonConverter
    {
        internal static readonly string DefaultDiscriminatorName = "discriminator";

        private readonly string _discriminatorName;

        [System.ThreadStatic]
        private static bool _isReading;

        [System.ThreadStatic]
        private static bool _isWriting;

        public JsonInheritanceConverter()
        {
            _discriminatorName = DefaultDiscriminatorName;
        }

        public JsonInheritanceConverter(string discriminatorName)
        {
            _discriminatorName = discriminatorName;
        }

        public string DiscriminatorName { get { return _discriminatorName; } }

        public override void WriteJson(Newtonsoft.Json.JsonWriter writer, object value, Newtonsoft.Json.JsonSerializer serializer)
        {
            try
            {
                _isWriting = true;

                var jObject = Newtonsoft.Json.Linq.JObject.FromObject(value, serializer);
                jObject.AddFirst(new Newtonsoft.Json.Linq.JProperty(_discriminatorName, GetSubtypeDiscriminator(value.GetType())));
                writer.WriteToken(jObject.CreateReader());
            }
            finally
            {
                _isWriting = false;
            }
        }

        public override bool CanWrite
        {
            get
            {
                if (_isWriting)
                {
                    _isWriting = false;
                    return false;
                }
                return true;
            }
        }

        public override bool CanRead
        {
            get
            {
                if (_isReading)
                {
                    _isReading = false;
                    return false;
                }
                return true;
            }
        }

        public override bool CanConvert(System.Type objectType)
        {
            return true;
        }

        public override object ReadJson(Newtonsoft.Json.JsonReader reader, System.Type objectType, object existingValue, Newtonsoft.Json.JsonSerializer serializer)
        {
            var jObject = serializer.Deserialize<Newtonsoft.Json.Linq.JObject>(reader);
            if (jObject == null)
                return null;

            var discriminatorValue = jObject.GetValue(_discriminatorName);
            var discriminator = discriminatorValue != null ? Newtonsoft.Json.Linq.Extensions.Value<string>(discriminatorValue) : null;
            var subtype = GetObjectSubtype(objectType, discriminator);

            var objectContract = serializer.ContractResolver.ResolveContract(subtype) as Newtonsoft.Json.Serialization.JsonObjectContract;
            if (objectContract == null || System.Linq.Enumerable.All(objectContract.Properties, p => p.PropertyName != _discriminatorName))
            {
                jObject.Remove(_discriminatorName);
            }

            try
            {
                _isReading = true;
                return serializer.Deserialize(jObject.CreateReader(), subtype);
            }
            finally
            {
                _isReading = false;
            }
        }

        private System.Type GetObjectSubtype(System.Type objectType, string discriminator)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType), true))
            {
                if (attribute.Key == discriminator)
                    return attribute.Type;
            }

            return objectType;
        }

        private string GetSubtypeDiscriminator(System.Type objectType)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType), true))
            {
                if (attribute.Type == objectType)
                    return attribute.Key;
            }

            return objectType.Name;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Combinator)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<NeuropixelsV2eHeadstage>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<NeuropixelsV2eBetaHeadstage>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Headstage64>))]
    public partial class MatchHeadstage : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = Type;
            var returnType = typeMapping != null ? typeMapping.GetType().GetGenericArguments()[0] : typeof(Headstage);
            return System.Linq.Expressions.Expression.Call(
                typeof(MatchHeadstage),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

    
        private static System.IObservable<TResult> Process<TResult>(System.IObservable<Headstage> source)
            where TResult : Headstage
        {
            return System.Reactive.Linq.Observable.Create<TResult>(observer =>
            {
                var sourceObserver = System.Reactive.Observer.Create<Headstage>(
                    value =>
                    {
                        var match = value as TResult;
                        if (match != null) observer.OnNext(match);
                    },
                    observer.OnError,
                    observer.OnCompleted);
                return System.ObservableExtensions.SubscribeSafe(source, sourceObserver);
            });
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into JSON strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into JSON strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToJson
    {
    
        public Newtonsoft.Json.Formatting Formatting { get; set; }

        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            var formatting = Formatting;
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.SerializeObject(value, formatting));
        }

        public System.IObservable<string> Process(System.IObservable<Headstage> source)
        {
            return Process<Headstage>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Headstage64> source)
        {
            return Process<Headstage64>(source);
        }

        public System.IObservable<string> Process(System.IObservable<NeuropixelsV2BetaProbe> source)
        {
            return Process<NeuropixelsV2BetaProbe>(source);
        }

        public System.IObservable<string> Process(System.IObservable<NeuropixelsV2Probe> source)
        {
            return Process<NeuropixelsV2Probe>(source);
        }

        public System.IObservable<string> Process(System.IObservable<NeuropixelsV2eBetaHeadstage> source)
        {
            return Process<NeuropixelsV2eBetaHeadstage>(source);
        }

        public System.IObservable<string> Process(System.IObservable<NeuropixelsV2eHeadstage> source)
        {
            return Process<NeuropixelsV2eHeadstage>(source);
        }

        public System.IObservable<string> Process(System.IObservable<EphysConfiguration> source)
        {
            return Process<EphysConfiguration>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of JSON strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of JSON strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Headstage>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Headstage64>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<NeuropixelsV2BetaProbe>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<NeuropixelsV2Probe>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<NeuropixelsV2eBetaHeadstage>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<NeuropixelsV2eHeadstage>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<EphysConfiguration>))]
    public partial class DeserializeFromJson : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromJson()
        {
            Type = new Bonsai.Expressions.TypeMapping<EphysConfiguration>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromJson),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.DeserializeObject<T>(value));
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.AttributeUsageAttribute((System.AttributeTargets.Class | System.AttributeTargets.Interface))]
    public class YamlDiscriminatorAttribute : System.Attribute
    {
    
        public YamlDiscriminatorAttribute(string discriminator)
        {
            Discriminator = discriminator;
        }

        public string Discriminator { get; private set; }

    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    public class YamlDiscriminatorTypeInspector : YamlDotNet.Serialization.TypeInspectors.ReflectionTypeInspector
    {
    
        readonly YamlDotNet.Serialization.ITypeInspector innerTypeDescriptor;

        public YamlDiscriminatorTypeInspector(YamlDotNet.Serialization.ITypeInspector innerTypeDescriptor)
        {
            if (innerTypeDescriptor == null)
            {
                throw new System.ArgumentNullException("innerTypeDescriptor");
            }

            this.innerTypeDescriptor = innerTypeDescriptor;
        }

        public override System.Collections.Generic.IEnumerable<YamlDotNet.Serialization.IPropertyDescriptor> GetProperties(System.Type type, object container)
        {
            var innerProperties = innerTypeDescriptor.GetProperties(type, container);

            var discriminatorAttribute = (YamlDiscriminatorAttribute)System.Attribute.GetCustomAttribute(type, typeof(YamlDiscriminatorAttribute));
            var inheritanceAttributes = (JsonInheritanceAttribute[])System.Attribute.GetCustomAttributes(type, typeof(JsonInheritanceAttribute));
            var typeMatch = System.Array.Find(inheritanceAttributes, attribute => attribute.Type == type);
            if (discriminatorAttribute != null && typeMatch != null)
            {
                return System.Linq.Enumerable.Concat(new[]
                {
                    new DiscriminatorPropertyDescriptor(discriminatorAttribute.Discriminator, typeMatch.Key)
                }, innerProperties);
            }

            return innerProperties;
        }

        class DiscriminatorPropertyDescriptor : YamlDotNet.Serialization.IPropertyDescriptor
        {
            readonly string key;

            public DiscriminatorPropertyDescriptor(string discriminator, string value)
            {
                ScalarStyle = YamlDotNet.Core.ScalarStyle.Plain;
                Name = discriminator;
                key = value;
            }

            public string Name { get; private set; }

            public bool Required
            {
                get { return true; }
            }

            public bool CanWrite
            {
                get { return true; }
            }

            public System.Type Type
            {
                get { return typeof(string); }
            }

            public System.Type TypeOverride { get; set; }

            public System.Type ConverterType
            {
                get { return null; }
            }

            public bool AllowNulls
            {
                get { return false; }
            }

            public int Order { get; set; }

            public YamlDotNet.Core.ScalarStyle ScalarStyle { get; set; }

            public T GetCustomAttribute<T>() where T : System.Attribute
            {
                return null;
            }

            public YamlDotNet.Serialization.IObjectDescriptor Read(object target)
            {
                return new YamlDotNet.Serialization.ObjectDescriptor(key, Type, Type, ScalarStyle);
            }

            public void Write(object target, object value)
            {
            }
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into YAML strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into YAML strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToYaml
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.SerializerBuilder()
                    .WithTypeInspector(inspector => new YamlDiscriminatorTypeInspector(inspector))
                      .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                      .Build();
                return System.Reactive.Linq.Observable.Select(source, value => serializer.Serialize(value)); 
            });
        }

        public System.IObservable<string> Process(System.IObservable<Headstage> source)
        {
            return Process<Headstage>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Headstage64> source)
        {
            return Process<Headstage64>(source);
        }

        public System.IObservable<string> Process(System.IObservable<NeuropixelsV2BetaProbe> source)
        {
            return Process<NeuropixelsV2BetaProbe>(source);
        }

        public System.IObservable<string> Process(System.IObservable<NeuropixelsV2Probe> source)
        {
            return Process<NeuropixelsV2Probe>(source);
        }

        public System.IObservable<string> Process(System.IObservable<NeuropixelsV2eBetaHeadstage> source)
        {
            return Process<NeuropixelsV2eBetaHeadstage>(source);
        }

        public System.IObservable<string> Process(System.IObservable<NeuropixelsV2eHeadstage> source)
        {
            return Process<NeuropixelsV2eHeadstage>(source);
        }

        public System.IObservable<string> Process(System.IObservable<EphysConfiguration> source)
        {
            return Process<EphysConfiguration>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of YAML strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of YAML strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Headstage>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Headstage64>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<NeuropixelsV2BetaProbe>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<NeuropixelsV2Probe>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<NeuropixelsV2eBetaHeadstage>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<NeuropixelsV2eHeadstage>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<EphysConfiguration>))]
    public partial class DeserializeFromYaml : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromYaml()
        {
            Type = new Bonsai.Expressions.TypeMapping<EphysConfiguration>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromYaml),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static void AddTypeDiscriminator<T>(YamlDotNet.Serialization.BufferedDeserialization.ITypeDiscriminatingNodeDeserializerOptions o)
        {
            var baseType = typeof(T);
            var discriminator = System.Reflection.CustomAttributeExtensions.GetCustomAttribute<YamlDiscriminatorAttribute>(baseType).Discriminator;
            var typeMapping = System.Linq.Enumerable.ToDictionary(
                System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(baseType),
                attr => attr.Key,
                attr => attr.Type);
            o.AddKeyValueTypeDiscriminator<T>(discriminator, typeMapping);
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.DeserializerBuilder()
                    .WithTypeInspector(inspector => new YamlDiscriminatorTypeInspector(inspector))
                    .WithTypeDiscriminatingNodeDeserializer(o =>
                    {
                        AddTypeDiscriminator<Headstage>(o);
                    })
                      .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                      .Build();
                return System.Reactive.Linq.Observable.Select(source, value =>
                {
                    var reader = new System.IO.StringReader(value);
                    var parser = new YamlDotNet.Core.MergingParser(new YamlDotNet.Core.Parser(reader));
                    return serializer.Deserialize<T>(parser);
                });
            });
        }
    }
}