name: CI-Audit
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  ContinuousIntegrationBuild: true
jobs:
  audit:
    strategy:
      fail-fast: false
      matrix:
        configuration: [debug, release]
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            test-filter: --filter TestCategory!=DriverDependent
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
     
    - name: Restore
      run: dotnet restore
 
    - name: Build
      run: dotnet build --no-restore --configuration ${{ matrix.configuration }}

    - name: Pack
      run: dotnet pack --no-build --configuration ${{ matrix.configuration }}

    - name: Test
      run: dotnet test --no-build --configuration ${{ matrix.configuration }} ${{ matrix.test-filter }}